FROM apache/airflow:2.9.3-python3.10

USER root

# Instala Java 17 (para PySpark)
RUN apt-get update \
    && apt-get install -y --no-install-recommends openjdk-17-jre-headless build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/

ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ENV PATH="$JAVA_HOME/bin:$PATH"

USER airflow

COPY app/requirements.txt /requirements.txt
RUN pip install --no-cache-dir -r /requirements.txt
